interface cardProps {
    isStolen?:string
    isHeirloom?:string
    pictures?:string
    category?:string
    subcategory?:string
    brand?:string
    breed?:string
    size?:string
    purchasedFrom?:string
    purchasedValue?:string
    reportedStolenDate?:string
    description?:string
    crypto_token_address?:string
    unique_features?:string
    artist?:string
    author?:string
    dob?:string
    body_length?:string
    brand_reference?:string
    caliber?:string
    carat_weight?:string
    case_material?:string
    cOfAuth?:string
    clarity?:string
    color?:string
    cut?:string
    date?:string
    dial?:string
    distinguishing_features?:string
    document?:string
    drivetrain?:string
    engine?:string
    engraving?:string
    exchange_address?:string
    exterior_color?:string
    fuel_type?:string
    grading?:string
    grading_reports?:string
    height?:string
    hotstamping?:string
    interior_color?:string
    invoice?:string
    laser_inscription?:string
    manufacturer?:string
    material?:string
    microchip?:string
    mileage?:string
    model?:string
    model_yr?:string
    movement_caliber?:string
    other?:string
    pedigree?:string
    product?:string
    registration_certificate?:string,
    release_date?:string
    serial?:string
    serie?:string
    series?:string
    shape?:string
    smart_contract_address?:string
    smart_contract_id?:string
    stock_number?:string
    stone?:string
    strap_bracelet?:string
    tattoo?:string
    trademarks?:string
    transaction?:string
    transmission?:string
    url?:string
    valuation_report?:string
    vin?:string
    wallet_address?:string
    weight?:string
    year?:string
    marketPrice?:string
    childIdFirstName?:string
    childIdMiddleName?:string
    childIdLastName?:string
    eye_color?:string
    hair_color?:string
    parentOneName?:string
    parentTwoName?:string
    contactNumberOne?:string
    contactNumberTwo?:string
    homeAddress?:string
    homeCity?:string
    homeState?:string
    homeCountry?:string
    homeZIP?:string
    age?:string
    gender?:string
    race?:string
    physicalTraits?:string
    allergies?:string
    medicalConditions?:string
    prescription?:string
    backgroundColor?:string
  }
    export let cardProps:cardProps = {
    isStolen,
    isHeirloom,
    pictures,
    category,
    subcategory,
    brand,
    breed,
    size,
    purchasedFrom,
    purchasedValue,
    reportedStolenDate,
    description,
    crypto_token_address,
    unique_features,
    artist,
    author,
    dob,
    body_length,
    brand_reference,
    caliber,
    carat_weight,
    case_material,
    cOfAuth,
    clarity,
    color,
    cut,
    date,
    dial,
    distinguishing_features,
    document,
    drivetrain,
    engine,
    engraving,
    exchange_address,
    exterior_color,
    fuel_type,
    grading,
    grading_reports,
    height,
    hotstamping,
    interior_color,
    invoice,
    laser_inscription,
    manufacturer,
    material,
    microchip,
    mileage,
    model,
    model_yr,
    movement_caliber,
    other,
    pedigree,
    product,
    registration_certificate,
    release_date,
    serial,
    serie,
    series,
    shape,
    smart_contract_address,
    smart_contract_id,
    stock_number,
    stone,
    strap_bracelet,
    tattoo,
    trademarks,
    transaction,
    transmission,
    url,
    valuation_report,
    vin,
    wallet_address,
    weight,
    year,
    marketPrice,
    childIdFirstName,
    childIdMiddleName,
    childIdLastName,
    eye_color,
    hair_color,
    parentOneName,
    parentTwoName,
    contactNumberOne,
    contactNumberTwo,
    homeAddress,
    homeCity,
    homeState,
    homeCountry,
    homeZIP,
    age,
    gender,
    race,
    physicalTraits,
    allergies,
    medicalConditions,
    prescription,
    backgroundColor,
  };