import mongoost from 'mongoose';
const childIdSchema = new mongoose.Schema({
    firstName: { type: String, default: "", required: true  },
    middleName: { type: String, default: "", required: true  },
    lastName: { type: String, default: "", required: true  },
    parent1Name: { type: String, default: "", required: true  },
    parent2Name: { type: String, default: "", required: true  },
    contactNumber1: { type: String, default: "", required: true  },
    contactNumber2: { type: String, default: "", required: true  },
    homeAddress: { type: String, default: "", required: true  },
    homeCity: { type: String, default: "", required: true  },
    homeState: { type: String, default: "", required: true  },
    homeZip: { type: String, default: "", required: true  },
    homeCountry: { type: String, default: "", required: true  },
    age: { type: String, default: "", required: true  },
    dateOfBirth: { type: String, default: "", required: true  },
    gender: { type: String, default: "", required: true  },
    race: { type: String, default: "", required: true  },
    height: { type: String, default: "", required: true  },
    weight: { type: String, default: "", required: true  },
    hairColor: { type: String, default: "", required: true  },
    eyeColor: { type: String, default: "", required: true  },
    physicalTraits: { type: [String], default: "", required: true  },
    allergy: { type: [String], default: "", required: true  },
    medicalCondition: { type: [String], default: "", required: true  },
    rx: { type: [String], default: "", required: true  },
    description: { type: String, default: "", required: true  },
    otherFeatures: { type: [String], default: "", required: true  },
    });
const ChildIdCard = mongoose.model("ChildIdCard", cardSchema);
    