<script lang="ts">
  import CardVault from "$lib/components/CardVault.svelte";
  import DesktopWidget from "$lib/components/DesktopWidget.svelte";

  import {
    Tab,
    TabGroup,
    TabList,
    TabPanel,
    TabPanels,
  } from "@rgossiaux/svelte-headlessui";
  import { quintOut } from "svelte/easing";
  import { fade, fly } from "svelte/transition";
  import PageContainer from "./PageContainer.svelte";
  let open = false;
  let tabs = [
    "Card Vault",
    "Import",
    "Request History Report",
    "Request Item Certificate",
    "Download Inventory",
    "Search",
  ];
  let contents = [
    "Card Vault",
    "Import",
    "Request History ",
    "Request Item Certificate",
    "Download Inventory",
    
  ];
  export let myneCards: any
  export let isLoading: boolean;
</script>
<PageContainer>
  <TabGroup defaultIndex={0} class="flex flex-col w-full h-[94vh] justify-center rounded-lg ">
    <TabList
      class={"flex font-bold justify-center text-primary rounded-lg p-1"}
    >
      <div class="flex justify-center content-center w-full shadow-sm">
        {#each tabs as tab}
          <Tab
            class={({ selected }) =>
              selected
                ? "flex flex-col flex-wrap content-center justify-center rounded-lg flex-1 bg-primary text-secondary p-1 slide-in-left"
                : "flex flex-col flex-wrap flex-1  content-center justify-center rounded-lg p-1"}
          >
            {tab}
          </Tab>
        {/each}
      </div>
    </TabList>

    <TabPanels class="w-full h-full relative rounded-lg p-2">
      {#each contents as content}
          <TabPanel class = 'w-full h-full absolute'>
            {#if content != "Card Vault"}
              <DesktopWidget title={content} />
            {:else}
              <CardVault myneCards = {myneCards} {isLoading}/>
              {/if}
          </TabPanel>
      {/each}
    </TabPanels>
  </TabGroup>
</PageContainer>
  
<!-- <AddCard/> -->

<style lang="postcss">
  * > :global(.selected) {
    background-color: rgb(191 219 254);
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-2-15 20:17:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
</style>
